export const VALIDATE_MESSAGES = {
    REQUIRED: 'required',
    INVALID_NUMBER: 'invalid-number',
    POSITIVE_NUMBER: 'positive-number',
    LESS_OR_EQUAL: 'less-or-equal',
    LARGER_OR_EQUAL: 'larger-or-equal',
    ONE_DECIMAL: 'one-decimal',
    SPECIAL_CHARACTERS: 'special-characters',
    NUMBER: 'number',
    MAX_LENGTH: 'max-length',
    SPECIAL_CHARACTERS_PARTER_NAME: 'special-characters-parter-name',
    SPECIAL_CHARACTERS_SUPPLIER_NAME: 'special-characters-supplier-name',
    NO_NUMBER: 'no-number',
    INVALID_EMAIL: 'invalid-email',
    INVALID_NAME_FILE: 'invalid-name-file',
};
